project_directory: "/home/tuc/MPW5/"

caravel:
    root:           /home/tuc/MPW5/caravel_user_project
    gl_dir:         /home/tuc/MPW5/caravel_user_project/verilog/gl
    test_dir:       /home/tuc/MPW5/caravel_user_project/verilog/dv
    rtl_dir:        /home/tuc/MPW5/caravel_user_project/verilog/rtl
    includes_dir:   /home/tuc/MPW5/caravel_user_project/verilog/includes/
    mgmt_root:      /home/tuc/MPW5/caravel_user_project/mgmt_core_wrapper/
    config:         config.tcl

env: # used for simulation
    GCC_PATH:       /home/tuc/MPW5/riscv64-unknown-elf-gcc-8.3.0-2020.04.1-x86_64-linux-ubuntu14/bin/
    GCC_PREFIX:     riscv64-unknown-elf
    PDK_PATH:       /home/tuc/MPW5/pdk/sky130A
    PDK_ROOT:       /home/tuc/MPW5/pdk
    OPENLANE:       /home/tuc/MPW5/openlane
    PDK:            sky130A
